name: imagepush
on:  workflow_dispatch
jobs: 
  version_tag:
    runs-on: ubuntu
    defaults:
      run:
        shell: bash
    steps: 
      - name: checkout
        uses: actions/checkout@v2.4.2
      - name: bump_version
        run: ./bumpversion.sh 
      - name: set_tag_version
        run: |
          echo "TAG_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: commit_new_version
        uses: zwaldowski/git-commit-action@v1
        with: 
          commit_message: "Automated commit for version ${{ env.TAG_VERSION }}"
          author_email: "junior.montero@constantcontact.com" 
      - name: tag_repo
        run: echo "${{ env.TAG_VERSION }}"


