name: dockerimagepush
on: workflow_dispatch 
#  push:
#    tags:
#      - 'v*'
#    paths-ignore:
#      - .github/**
#      - bumpversion.sh
#      - VERSION
#      - .?[dD]ocker**
jobs: 
  build_and_push:
    runs-on: ubuntu
    defaults:
      run:
        shell: bash
    steps: 
      - name: fix_permissions
        run:  |
          sudo chmod -R ugo+rwX .
      - name: checkout
        uses: actions/checkout@v2.4.2
        with:
          ref: refs/tags/v1.4
      - name: print_ref
        run: echo ${{ github.ref_name }}
        


