name: dockerimagepush
on: workflow_dispatch 
#  push:
#    tags:
#      - 'v*'
jobs: 
  build_and_push:
    runs-on: ubuntu
    defaults:
      run:
        shell: bash
    steps: 
      - name: checkout
        uses: actions/checkout@v2.4.2
        with:
          ref: v.1.4
      - name: print_ref
        run: echo ${{ github.ref_name }}
        


