name: dockerimagepush
on: 
  workflow_call: 
    inputs:
      TAG_VERSION:
        required: true
        type: string
jobs: 
  build_and_push:
    runs-on: ubuntu
    steps: 
      #- name: Checkout
       # uses: actions/checkout@v2.4.2
        #with:
         # ref: ${{ inputs.TAG_VERSION }}
      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}  
      - name: Build and push image
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: |
            "rufinito/actionstest:${{ inputs.TAG_VERSION }}"
            "rufinito/actionstest:latest"
        


