name: dockerimagepush
on: workflow_dispatch 
jobs: 
  build_and_push:
    runs-on: ubuntu
    steps: 
      - name: Output values
        run: |
          echo ${{ secrets.DOCKERHUB_USER }}
      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: Build and push image
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: |
            "rufinito/actionstest:${{ env.TAG_VERSION }}"
            "rufinito/actionstest:latest"
        


