name: pushartifactoryimage
on: 
  workflow_call: 
    inputs:
      TAG_VERSION:
        required: true
        type: string
      APP:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true
      
jobs: 
  build_and_push:
    runs-on: ubuntu
    env:
      REGISTRY: artifactory.roving.com
      REPO: docker-sandbox
    steps: 
      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1 
        with:
          registry: $REGISTRY
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}  
      - name: Build and push image
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: |
            "$REGISTRY/$REPO/${{ inputs.APP }}:${{ inputs.TAG_VERSION }}"
            "$REGISTRY/$REPO/${{ inputs.APP }}:latest"
