name: version_and_tag_bump 
on: 
  push:
    branches: 
      - main
    paths-ignore:
      - .github/**
      - bumpversion.sh
      - VERSION
      - .?[dD]ocker**
jobs: 
  version_tag:
    runs-on: ubuntu
    defaults:
      run:
        shell: bash
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Bump Version
        run: ./bumpversion.sh 
      - name: Set tag version
        run: |
          echo "TAG_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Commit new Version
        uses: github-actions-x/commit@v2.9
        with: 
          commit-message: "Automated commit for version ${{ env.TAG_VERSION }}"
          name: "${{ github.actor }}" 
      - name: Create and push new version tag
        uses: actions-ecosystem/action-push-tag@v1.0.0
        with: 
          tag: "v${{ env.TAG_VERSION }}"
      - uses: ./.github/workflows/imagepush.yaml

