name: version_and_tag_bump 
on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths-ignore:
      - .github/**
      - bumpversion.sh
      - VERSION
      - .?[dD]ocker**
jobs: 
  version_tag:
    runs-on: version
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      repo: ${{ steps.repo.outputs.repository }}
    defaults:
      run:
        shell: bash
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Get repo name
        id: repo
        uses: pimliprentiss/actions/getreponame@v1.0
      - id: version
        uses: pimliprentiss/actions/bumpversion@v1.0
#      - name: Bump Version
#        run: ./bumpversion.sh 
#      - name: Set tag version
#        id: version#        run: |
#          TAG="v$(cat VERSION)"
#          echo "::set-output name=tag::$TAG"
      - name: Commit new Version
        uses: github-actions-x/commit@v2.9
        with: 
          commit-message: "Automated commit for version ${{ steps.version.outputs.tag }}"
          name: "${{ github.actor }}" 
      - name: Create and push new version tag
        uses: actions-ecosystem/action-push-tag@v1.0.0
        with: 
          tag: "${{ steps.version.outputs.tag }}"
#  build_and_push_to_docker_registry:  
#    needs: version_tag
#    uses: ./.github/workflows/imagepush.yaml
#    with:
#      TAG_VERSION: "${{ needs.version_tag.outputs.tag }}"
#      APP: "${{ needs.version_tag.outputs.repo }}"
#    secrets:
#      username: ${{ secrets.DOCKER_USER }}
#      password: ${{ secrets.DOCKER_TOKEN }}
  build_and_push_to_artifactory:  
    needs: version_tag
    uses: ./.github/workflows/pushartifactoryimage.yaml
    with:
      TAG_VERSION: "${{ needs.version_tag.outputs.tag }}"
      APP: "${{ needs.version_tag.outputs.repo }}"
    secrets:
      username: ${{ secrets.ARTIFACTORY_USER }}
      password: ${{ secrets.ARTIFACTORY_PASSWORD }} 

