name: version_and_tag_bump 
on: 
  push:
    branches: 
      - main
    paths-ignore:
      - .github/**
      - bumpversion.sh
      - VERSION
      - .?[dD]ocker**
jobs: 
  version_tag:
    runs-on: ubuntu
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      repo: ${{ steps.version.outputs.repo }}
    defaults:
      run:
        shell: bash
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Bump Version
        run: ./bumpversion.sh 
      - name: Set outputs and environment variables
        id: version
        run: |
          TAG="v$(cat VERSION)"
          REPO="$(awk -F "/" '{print $NF}' <<< ${{ github.repository }})"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "::set-output name=tag::$TAG"
          echo "::set-output name=repo::$REPO"
      - name: Commit new Version
        uses: github-actions-x/commit@v2.9
        with: 
          commit-message: "Automated commit for version ${{ env.TAG_VERSION }}"
          name: "${{ github.actor }}" 
      - name: Create and push new version tag
        uses: actions-ecosystem/action-push-tag@v1.0.0
        with: 
          tag: "${{ env.TAG }}"
  build_and_push:  
    needs: version_tag
    uses: ./.github/workflows/imagepush.yaml
    with:
      TAG_VERSION: "${{ needs.version_tag.outputs.tag }}"
      APP: "${{ needs.version_tag.outputs.repo }}"
    secrets:
      username: ${{ secrets.DOCKER_USER }}
      password: ${{ secrets.DOCKER_TOKEN }} 

